name: as2

on: [push]

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
                
    test-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install Flask
            - uses: AppThreat/sast-scan-action@master
              with:
                type: "python"
            - run: echo "teste! :D"

    deploy-job:
        needs: [test-job]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker
              uses: docker/login-action@v3
              with:
                username: karrigok
                password: dinkiuinki123
            
            - name: Build Docker Image
              run: docker build -t karrigok/devops-as2:latest .

            - name: Push Docker Build
              run: docker push karrigok/devops-as2:latest

            - name: Notificacao Telegram
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                message: "A implantação da aplicação foi concluída com sucesso!"

            - name: Exibe msg de finalizacao
              run: echo "Finalizado com Sucesso :D"
